import os

HYDROGRAPH_CSV = 'hydrograph.csv'
HYDROGRAPH_TXT = 'hydrograph.txt'
HSM1_CSV = 'hsm1.csv'
WAT_PAYLOAD_AZ_YML = 'wat_payload_az.yml'
WAT_PAYLOAD_AWS_YML = 'wat_payload_aws.yml'
WAT_PAYLOAD_REDIS_YML = 'wat_payload_redis.yml'
CONFIG_AZ_YML = 'config_az.yml'
CONFIG_AWS_YML = 'config_aws.yml'
CONFIG_REDIS_YML = 'config_redis.yml'
TESTS_DATA = './tests/data'
PATH_HYDROGRAPH_CSV = os.path.join(TESTS_DATA, HYDROGRAPH_CSV)
PATH_HYDROGRAPH_TXT = os.path.join(TESTS_DATA, HYDROGRAPH_TXT)
PATH_HSM1_CSV = os.path.join(TESTS_DATA, HSM1_CSV)
PATH_WAT_PAYLOAD_AZ_YML = os.path.join(TESTS_DATA, WAT_PAYLOAD_AZ_YML)
PATH_WAT_PAYLOAD_AWS_YML = os.path.join(TESTS_DATA, WAT_PAYLOAD_AWS_YML)
PATH_WAT_PAYLOAD_REDIS_YML = os.path.join(TESTS_DATA, WAT_PAYLOAD_REDIS_YML)
PATH_CONFIG_AZ_YML = os.path.join(TESTS_DATA, CONFIG_AZ_YML)
PATH_CONFIG_AWS_YML = os.path.join(TESTS_DATA, CONFIG_AWS_YML)
PATH_CONFIG_REDIS_YML = os.path.join(TESTS_DATA, CONFIG_REDIS_YML)